# Generated by Django 6.1.1 on 2026-09-19 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Undefined', max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('project', models.CharField(choices=[('studies', 'Studies'), ('projects', 'Projects'), ('personal', 'Personal')], default='studies', max_length=50)),
                ('priority', models.CharField(choices=[('short', 'Short'), ('average', 'Average'), ('high', 'High')], default='short', max_length=50)),
                ('date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
